-- --==============================================================
-- -- The Insulines
-- -- Copyright (c) 2010-2012 quov.is
-- -- All Rights Reserved. 
-- -- http://quov.is // http://theinsulines.com
-- --==============================================================
-- 

-- mainCharacter = character.new ( 'main_character' )
-- mainCharacter.renderPriority = 200
-- nancy = character.new ( 'nancy' )
-- nancy.renderPriority = 100